import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import Card from "../components/card";
import styles from "../styles/Home.module.css";

export default function Home() {
  const handleViewBtnClick = () => {
    console.log("hi");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee shops info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText={"view Stores"} onClick={handleViewBtnClick} />
        <div className={styles.heroImage}>
          <Image src={"/static/hero-image.png"} width={700} height={400} />
        </div>
        <div className={styles.cardLayout}>
          <Card
            name={"danje"}
            href={"/Danje-Coffee"}
            imageSrc={"/static/hero-image.png"}
          />
          <Card
            name={"danje"}
            href={"/Danje-Coffee"}
            imageSrc={"/static/hero-image.png"}
          />
          <Card
            name={"danje"}
            href={"/Danje-Coffee"}
            imageSrc={"/static/hero-image.png"}
          />
          <Card
            name={"danje"}
            href={"/Danje-Coffee"}
            imageSrc={"/static/hero-image.png"}
          />
        </div>
      </main>
    </div>
  );
}
